// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PictureEngineer.Data;

namespace PictureEngineer.Data.Migrations
{
    [DbContext(typeof(PictureEngineerDbContext))]
    [Migration("20210809170234_create-table")]
    partial class createtable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("ROLES");

                    b.HasData(
                        new { Id = "1", ConcurrencyStamp = "b61ac4d3-eeea-4da2-b8cc-864eb375f04e", Name = "Quản trị viên", NormalizedName = "ADMIN" },
                        new { Id = "2", ConcurrencyStamp = "bca38043-7fe2-4c02-9e93-e22e37912465", Name = "Thành viên", NormalizedName = "MEMBER" }
                    );
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("ROLE_CLAIMS");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("USER_CLAIMS");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("USER_LOGINS");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("USER_ROLES");

                    b.HasData(
                        new { UserId = "8a51ce96-a182-41d3-944f-9addccce84ba", RoleId = "1" }
                    );
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("USER_TOKENS");
                });

            modelBuilder.Entity("PictureEngineer.Data.Entities.AspNetUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FullName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("Picture");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("USERS");

                    b.HasData(
                        new { Id = "8a51ce96-a182-41d3-944f-9addccce84ba", AccessFailedCount = 0, ConcurrencyStamp = "a7509d88-e614-45ac-b424-0ec59c25454c", Email = "binhhp20@gmail.com", EmailConfirmed = true, FullName = "Vu Tat Binh", LockoutEnabled = true, NormalizedEmail = "BINHHP20@GMAIL.COM", NormalizedUserName = "BINHHP20", PasswordHash = "AQAAAAEAACcQAAAAEIbHIX20zSBhbwLgoHNk2ZbvWL5R5wQSfPqnepjoBYfYpVhw9o7jIk12i7iDKNlA+A==", PhoneNumber = "0965788640", PhoneNumberConfirmed = false, Picture = "https://firebasestorage.googleapis.com/v0/b/pengineer-42d51.appspot.com/o/users%2F1596889689_912_Anh-avatar-dep-va-doc-dao-lam-hinh-dai-dien.jpg?alt=media&token=3db2e79f-8701-4ae7-be90-66f7b376735a", SecurityStamp = "6PPOTFQNHXOLMB5IP2NDIA2DDCQPXU4L", TwoFactorEnabled = false, UserName = "binhhp20" }
                    );
                });

            modelBuilder.Entity("PictureEngineer.Data.Entities.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contents")
                        .IsRequired();

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("ImageName")
                        .IsRequired();

                    b.Property<string>("ImagePath")
                        .IsRequired();

                    b.Property<string>("MetaTitle")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("ServiceId");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("BLOG");
                });

            modelBuilder.Entity("PictureEngineer.Data.Entities.FAQs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer");

                    b.Property<string>("Question");

                    b.Property<int>("ServiceID");

                    b.HasKey("Id");

                    b.ToTable("FAQS");

                    b.HasData(
                        new { Id = 1, Answer = "Mục tiêu chính đằng sau PEngineer.com là cung cấp trải nghiệm hoàn toàn miễn phí cho người dùng của chúng tôi. Do đó, chúng tôi nhận mọi gánh nặng cuối cùng của chúng tôi. KHÔNG CẦN CÀI ĐẶT BẤT KỲ PHẦN MỀM NÀO trên máy tính xách tay, PC, điện thoại thông minh của bạn, vv .. Điều này hoàn toàn trực tuyến.", Question = "Bạn có yêu cầu bất kỳ phần mềm nào được tải xuống hay hoàn toàn trực tuyến không?", ServiceID = 0 },
                        new { Id = 2, Answer = "Dữ liệu được truyền bằng HTTPS thông qua mã hóa 256 bit. Tất cả các tệp bạn tải lên máy chủ của chúng tôi cho các hoạt động khác nhau sẽ tự động bị xóa trong vòng một giờ. Bảo mật là ưu tiên hàng đầu của chúng tôi.", Question = "Làm thế nào là an toàn để sử dụng cái này?", ServiceID = 0 },
                        new { Id = 3, Answer = "Chúng tôi đã xây dựng công cụ trực tuyến này với mong muốn đóng góp cho cộng đồng. Chúng tôi không có ý định tính phí bất cứ thứ gì từ người dùng.Tuy nhiên, chúng tôi có thể chạy Quảng cáo để hỗ trợ sáng kiến ​​này.", Question = "Công cụ là miễn phí và không giới hạn?", ServiceID = 0 },
                        new { Id = 4, Answer = "Chúng tôi hiện đang phát triển công cụ và nhận diện tốt nhất. Tuy nhiên, thời gian xử lý và nhận diện vẫn còn bị hạn chế nhưng sẽ được cải thiện nếu bạn chụp ảnh rõ nét, chi tiết xem dưới công cụ.", Question = "Nhận diện ảnh chụp như thế nào, làm sao để đạt độ chính xác cao?", ServiceID = 0 },
                        new { Id = 5, Answer = "Picture Engineer là một công cụ trực tuyến 100% và hoạt động bên trong trình duyệt web. Vì vậy, không thành vấn đề cho dù bạn đang sử dụng Microsoft Windows, Mac OS, Linux, iOS, Android hay bất kỳ hệ điều hành nào khác. Nếu hệ điều hành của bạn hỗ trợ bất kỳ trình duyệt hiện đại tiêu chuẩn nào như Google Chrome, Firefox, Internet Explorer, Safari, v.v. thì bạn có thể sử dụng công cụ một cách liền mạch.", Question = "Bạn có thể nêu chi tiết các hệ điều hành được công cụ hỗ trợ trên máy tính để bàn và PC không?", ServiceID = 0 },
                        new { Id = 6, Answer = "Hiện tại công cụ là miễn phí và luôn đáp ứng tất cả mọi nhu cầu của người dùng", Question = "Công cụ nhận diện là miễn phí và không giới hạn?", ServiceID = 1 },
                        new { Id = 7, Answer = "Hiện tại chúng tôi mới chỉ phát triển nhận diện trên các ảnh chụp tài liệu văn bản nghiên cứu có các yếu tố như bảng, biểu đồ, biểu thức toán học, .... Tương lai chúng tôi sẽ phát triển thêm", Question = "Có thể nhận diện tất cả các hình ảnh chụp?", ServiceID = 1 },
                        new { Id = 8, Answer = "File ảnh được mã hóa base64 khi upload và xử lý sẽ xóa file. Chúng tôi không lưu lại tất cả các file.", Question = "Các file ảnh tài liệu của chúng tôi là an toàn?", ServiceID = 1 },
                        new { Id = 9, Answer = "Chúng tôi không chắc nhận diện được 100% nhưng sẽ đạt kết quả tốt như ý muốn nếu bạn thực hiện đúng với hướng dẫn bên trên của chúng tôi", Question = "Làm cách nào để công cụ nhận diện 100%?", ServiceID = 1 },
                        new { Id = 10, Answer = "Hiện tại công cụ nhận diện hỗ trợ ngôn ngữ tiếng anh và tiếng việt", Question = "Công cụ hỗ trợ ngôn ngữ nhận diện nào?", ServiceID = 1 },
                        new { Id = 11, Answer = "Có, bạn có thể lưu một hoặc nhiều trang từ một tệp PDF.Bạn có thể tách hoặc trích xuất các trang một cách dễ dàng bằng cách chọn các trang cần thiết từ tệp PDF đã tải lên và tải xuống riêng biệt tất cả cùng một lúc.", Question = "Tôi có thể lưu một trang PDF không?", ServiceID = 2 },
                        new { Id = 12, Answer = "Truy cập công cụ và tải lên tệp PDF mà bạn muốn trích xuất các trang từ đó. Chọn các trang bạn muốn tải xuống và lưu các trang đã chọn. Bạn cũng có thể chia tệp PDF thành hai và duy trì chất lượng và nội dung của tệp PDF gốc.", Question = "🔥 Làm thế nào để trích xuất các trang từ một pdf?", ServiceID = 2 },
                        new { Id = 13, Answer = "Không, PictureEngineer là một công cụ tiên tiến cao. Sử dụng công cụ chuyển đổi này, bạn phải yên tâm nhận được định dạng nội dung chính xác sẽ chỉ ở định dạng tệp mong muốn chuyển đổi. Với công cụ của chúng tôi, bạn sẽ không bao giờ bị mất định dạng nội dung gốc, điều này sẽ không bao giờ khiến bạn lo lắng trước khi tải xuống hoặc chia sẻ tệp đã chuyển đổi và mở tệp đó để chỉ cần kiểm tra xem nó có được chuyển đổi đúng cách hay không.", Question = "Tôi có bị mất định dạng nội dung khi chuyển đổi từ PDF sang Word không?", ServiceID = 3 },
                        new { Id = 14, Answer = "Chỉ cần ba bước kỳ diệu và bạn đã sẵn sàng để chuyển đổi tệp đúng cách: Bước 1: Tải lên tệp ở định dạng PDF mà bạn muốn chuyển đổi.Bạn có thể tải nó lên từ máy tính, máy tính bảng, máy tính xách tay, điện thoại thông minh hoặc các phương tiện lưu trữ đám mây Bước 2: Bây giờ hãy đợi một vài giây để tải lên và chuyển đổi tệp theo cách thích hợp. Bước 3: Bây giờ bạn có thể tải xuống hoặc chia sẻ tệp một cách rất dễ hiểu.", Question = "Làm thế nào để chuyển đổi một tệp PDF sang Word đúng cách?", ServiceID = 3 },
                        new { Id = 15, Answer = "Picture Engineer sử dụng máy chủ an toàn để cung cấp cho bạn dịch vụ chuyển đổi liền mạch. Nền tảng của chúng tôi an toàn và bảo mật 100% và không có sự can thiệp của bên thứ ba với chúng tôi. Bất kỳ tệp nào bạn tải lên hoặc tải xuống từ công cụ của chúng tôi, không bao giờ được chia sẻ với bất kỳ ai trong bất kỳ điều kiện nào. Chúng tôi hoàn toàn được tin cậy bởi hàng nghìn người dùng hàng ngày và chúng tôi đảm bảo rằng tính riêng tư của tài liệu của bạn luôn được duy trì.", Question = "Làm thế nào để chuyển đổi tệp Word mà không có bất kỳ mối đe dọa nào về quyền riêng tư?", ServiceID = 3 }
                    );
                });

            modelBuilder.Entity("PictureEngineer.Data.Entities.Files", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreate");

                    b.Property<string>("FileName");

                    b.HasKey("Id");

                    b.ToTable("FILES");
                });

            modelBuilder.Entity("PictureEngineer.Data.Entities.Services", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color");

                    b.Property<string>("Description");

                    b.Property<string>("Icon");

                    b.Property<string>("ImgPath");

                    b.Property<string>("Meta");

                    b.Property<string>("Name");

                    b.Property<int>("ParentID");

                    b.Property<string>("UserGuide");

                    b.HasKey("Id");

                    b.ToTable("SERVICES");

                    b.HasData(
                        new { Id = 1, Color = "rgb(248, 80, 196)", Description = "Nhận diện và chuyển đổi ảnh chụp văn bản tài liệu sang file docx", Icon = "https://s1.iaspire.tech/1/5561/ppt.svg.svg", ImgPath = "https://firebasestorage.googleapis.com/v0/b/pengineer-42d51.appspot.com/o/services%2Fpageicon_delete-icon.png?alt=media&token=e08dc9de-829a-45c6-b569-c82945af4c89", Meta = "nhan-dien", Name = "Nhận diện ảnh chụp tài liệu", ParentID = 1, UserGuide = "<h2>Cách nhận diện và chuyển đổi ảnh chụp tài liệu văn bản của bạn</h2><ul><li class='answer'><span>Với công cụ của chúng tôi nhận diện với độ chính xác 71.38%. Song để đạt độ chính xác cao nhất, bạn cần lưu ý sau:</span></li><li><i class='icon-circle-check'></i>&nbsp;&nbsp;Tải lên file ảnh của bạn từ thiết bị của bạn, cho phép các file ảnh dạng png, jpg, jpeg.</li><li><i class='icon-circle-check'></i>&nbsp;&nbsp;Ảnh chụp tài liệu cần rõ nét, bạn cần chụp ảnh ở giữa màn hình.</li><li><i class='icon-circle-check'></i>&nbsp;&nbsp;Loại bỏ các vật thể không liên quan đến tài liệu cần chụp trong ảnh.</li><li><i class='icon-circle-check'></i>&nbsp;&nbsp;Độ sáng tối vừa phải, dễ nhìn dễ nhận biết.</li></ul>" },
                        new { Id = 2, Color = "#20c997", Description = "Chia nhỏ tài liệu PDF lớn thành nhiều tài liệu", Icon = "https://firebasestorage.googleapis.com/v0/b/pengineer-42d51.appspot.com/o/services%2Fsplit.png?alt=media&token=58182cef-8307-4141-a46c-c312cd5248aa", ImgPath = "https://firebasestorage.googleapis.com/v0/b/pengineer-42d51.appspot.com/o/services%2Fpageicon_split-icon.png?alt=media&token=e01f124e-1fc0-4c95-98ee-e48f95da8d66", Meta = "tach-pdf", Name = "Tách PDF", ParentID = 2, UserGuide = "<h2>Cách trích xuất các trang từ tệp PDF của bạn</h2><ul><li><span>< i class='icon-circle-check'></i>&nbsp;&nbsp;Việc chia nhỏ PDF rất tiện lợi và chỉ mất vài phút.</li><li><i class='icon-circle-check'></i>&nbsp;&nbsp;Bạn có thể ✂ chia từng trang PDF thành các tệp riêng lẻ hoặc bạn có thể trích xuất các trang cụ thể bằng cách nhập phạm vi trang đã chọn.</li><li><i class='icon-circle-check'></i>&nbsp;&nbsp;Chúc mừng! Các tệp PDF của bạn đã sẵn sàng để tải xuống.</li></ul>" },
                        new { Id = 3, Color = "rgb(255, 46, 94)", Description = "Chuyển PDF sang Word hoặc Excel", Icon = "https://firebasestorage.googleapis.com/v0/b/pengineer-42d51.appspot.com/o/services%2Fexcel.png?alt=media&token=cf597d9c-497b-4fad-9215-01292087afd7", ImgPath = "https://firebasestorage.googleapis.com/v0/b/pengineer-42d51.appspot.com/o/services%2Fpageicon_pdf-icon.png?alt=media&token=a94b6bf3-3618-4912-a303-cded760e642a", Meta = "chuyen-doi-pdf", Name = "Chuyển định dạng PDF", ParentID = 2, UserGuide = "<h2>Các bước chuyển đổi PDF sang Docx trên Picture Engineer</h2><ul><li><span><i class='icon-circle-check'></i>&nbsp;&nbsp;Trước hết, bạn phải giữ cho tệp luôn sẵn sàng trong thiết bị của mình.</span></li><li><span><i class='icon-circle-check'></i>&nbsp;&nbsp;Sau đó, tải tệp của bạn muốn xử lý lên công cụ của chúng tôi.</span></li><li><i class='icon-circle-check'></i>&nbsp;&nbsp;Bạn lựa chọn cách thích hợp và xử lý</li><li><i class='icon-circle-check'></i>&nbsp;&nbsp;Cuối cùng bạn tải xuống file mới được tạo.</li></ul>" },
                        new { Id = 4, Color = "rgb(70, 134, 248)", Description = "Chuyển đổi Docx sang PDF", Icon = "https://firebasestorage.googleapis.com/v0/b/pengineer-42d51.appspot.com/o/services%2Fdoc.png?alt=media&token=a65feb42-5ad1-4757-b0ba-7de1e7379ba5", ImgPath = "https://firebasestorage.googleapis.com/v0/b/pengineer-42d51.appspot.com/o/services%2Fpageicon_doc-icon.png?alt=media&token=2bb0b3a6-2163-4550-94e9-196291afd34a", Meta = "chuyen-doi-docx", Name = "Chuyển đổi Docx sang PDF", ParentID = 2, UserGuide = "<h2>Các bước chuyển đổi PDF sang Docx trên Picture Engineer</h2><ul><li><span><i class='icon-circle-check'></i>&nbsp;&nbsp;Trước hết, bạn phải giữ cho tệp luôn sẵn sàng trong thiết bị của mình.</span></li><li><span><i class='icon-circle-check'></i>&nbsp;&nbsp;Sau đó, tải tệp của bạn muốn xử lý lên công cụ của chúng tôi.</span></li><li><i class='icon-circle-check'></i>&nbsp;&nbsp;Bạn lựa chọn cách thích hợp và xử lý</li><li><i class='icon-circle-check'></i>&nbsp;&nbsp;Cuối cùng bạn tải xuống file mới được tạo.</li></ul>" }
                    );
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PictureEngineer.Data.Entities.AspNetUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PictureEngineer.Data.Entities.AspNetUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PictureEngineer.Data.Entities.AspNetUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PictureEngineer.Data.Entities.AspNetUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
